---
title: "The PopuList Dashboard"
format: 
  dashboard:
    orientation: columns
    logo: images/logo.PNG
editor: visual
theme: cosmo
---

# General Overview

::: {.card title="**Party Information Per Country**"}
```{r}
#| echo: FALSE

library(tidyverse)
library(reactable)
library(gt)

populist_cleaned <- read_csv("/Users/lukefischer/Dropbox/The PopuList Repo/Data/processed_populist.csv")


reactable(
  populist_cleaned,
  groupBy = "Country",
  columns = list(
    "Populist" = 
      colDef(html = TRUE, width = 140, headerStyle = list(backgroundColor = "#f0f5f9")),
    "Far-Right" = 
      colDef(html = TRUE, width = 140, headerStyle = list(backgroundColor = "#f0f5f9")),
    "Far-Left" = 
      colDef(html = TRUE, width = 140, headerStyle = list(backgroundColor = "#f0f5f9")),
    "Eurosceptic" = 
      colDef(html = TRUE, width = 140, headerStyle = list(backgroundColor = "#f0f5f9")),
    "In Parliament" = 
      colDef(html = TRUE, width = 150, headerStyle = list(backgroundColor = "#f0f5f9")),
    "Abbr." = 
      colDef(html = TRUE, width = 110, headerStyle = list(backgroundColor = "#f0f5f9")),
    "Party Name" = 
      colDef(headerStyle = list(backgroundColor = "#f0f5f9")),
    "Name En." = 
      colDef(headerStyle = list(backgroundColor = "#f0f5f9")),
    "Country" = 
      colDef(
        width = 140,
        headerStyle = list(backgroundColor = "#f0f5f9"),
      grouped = JS("function(cellInfo) {
        return cellInfo.value
      }")
    )),
  highlight = TRUE,
  sortable = TRUE,
  defaultExpanded = FALSE,
  defaultPageSize = 6,
  searchable = TRUE,
  theme = reactableTheme(
    borderColor = "#dfe2e5",
    stripedColor = "#f6f8fa",
    highlightColor = "#f0f5f9",
    cellPadding = "8px 12px",
    style = list(
      fontFamily = "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif"),
    searchInputStyle = list(width = "100%")
  )
)
```
:::

# Further Explanation

## Column {width="25%"}

::: {.card title="**Symbol Legend**"}
The list under "General Overview" indicates whether or not a party is populist, far-right, far-left, eurosceptic, and currently in parliament. The table makes use of the following symbols:

| Party |                  Vote-Share (%) |
|-------|--------------------------------:|
| ●     | Party fulfills a characteristic |
| ◐     |      Party is a borderline case |
| ()    |                   Time interval |

For country specific reports, please refer to the [main website](https://popu-list.org/ "popu-list.org").
:::

## Column {width="75%"}

::: {.card title="**Classification Scheme**"}
| Category | Explanation |
|------------------------------------|:-----------------------------------|
| Populist | Parties that endorse the set of ideas that society is ultimately separated into two homogeneous and antagonistic groups, “the pure people” versus “the corrupt elite,” and which argues that politics should be an expression of the volonté générale (general will) of the people (Mudde 2004). |
| Euroskeptic | Parties that express the idea of contingent or qualified opposition, as well as incorporate outright and unqualified opposition to the process of European integration. This includes both “hard Euroskepticism” (i.e., outright rejection of the entire project of European political and economic integration, and opposition to one’s country joining or remaining a member of the EU) and “soft Euroskepticism” (i.e., contingent or qualified opposition to European integration; Taggart and Sczcerbiak 2004). |
| Far-Left | Parties that reject the underlying socio-economic structure of contemporary capitalism and advocate for alternative economic and power structures. They see economic inequality as the basis of existing political and social arrangements and call for a major redistribution of resources from existing political elites (March 2011). |
| Far-Right | Parties that are nativist (which is an ideology that holds that states should be inhabited exclusively by members of the native group and that non-native elements are fundamentally threatening to the homogenous nation-state) and authoritarian (which is the belief in a strictly ordered society, in which infringements of authority are to be punished severely; Mudde 2007). |
:::
