---
format: html
editor: visual
params:
  country: "test"
  longitude: 1
  latitude: 2
  text: "test"
  iso_code: "DEU"
---

```{r}
#| echo: FALSE
#| message: FALSE
#| warning: FALSE
library(tidyverse)
# Needs to be parametrized
P <- read_csv('/Users/lukefischer/Dropbox/The PopuList Repo/Data/P.csv')

country_key <- case_when(
  params$country == "United Kingdom" ~ "United_Kingdom",
  params$country == "Czech Republic" ~ "Czech_Republic",
  TRUE ~ params$country
)

P <- P |> filter(year == 2022 & country == country_key)
```

# `r params$country` PopuList Country Report

::::: columns
::: {.column width="40%"}
## 2022

The vote-share of far-left (populist), far-right (populist), and populist parties:

| Party              |               Vote-Share (%) |
|--------------------|-----------------------------:|
| Far-Left           |           `r P$left_votes` % |
| Far-Left Populist  |  `r P$left_populist_votes` % |
| Populist           |       `r P$populist_votes` % |
| Far-Right Populist | `r P$right_populist_votes` % |
| Far-Right          |          `r P$right_votes` % |
:::

::: {.column width="60%" style="margin-bottom: -200px;"}
```{r}
#| echo: FALSE
#| message: FALSE
#| warning: FALSE

library(plotly)

plot_ly(
  type = "choropleth",
  locations = params$iso_code,          
  z = 1,          
  width = 465,  
  height = 465, 
  locationmode = "ISO-3",
  colorscale = list(c(0, 1), c("#FFB3F8", "#FFB3F8")),
  showscale = FALSE,
  marker = list(line = list(color = "#FFB3F8", width = 2))
) |> 
  layout(
    #margin = list(l=10, r=0, t=0, b=10),
    geo = list(
      projection = list(
        type = "orthographic",
        scale = 3
      ),
      center = list(
        lon = params$longitude,
        lat = params$latitude
      ),
      showland = TRUE,
      landcolor = "#e4e4e4",
      showcoastlines = TRUE,
      coastlinecolor = "#e4e4e4",
      showocean = TRUE,
      oceancolor = "#DFFFFE",
      bgcolor = "rgba(0,0,0,0)",
      framecolor = "rgba(0,0,0,0)"
    )
) |> 
  config(displayModeBar = FALSE)

```
:::
:::::

`r params$text`
