---
format: html
editor: visual
params:
  country: "test"
  longitude: 1
  latitude: 2
  text: "test"
  iso_code: "DEU"
---

```{r}
#| echo: FALSE
#| message: FALSE
#| warning: FALSE
library(tidyverse)
# Needs to be parametrized
P <- read_csv('/Users/lukefischer/Dropbox/The PopuList Repo/Data/P.csv')

P <- P |> 
  rename(country = country_name)

country_key <- case_when(
  params$country == "United Kingdom" ~ "United_Kingdom",
  params$country == "Czech Republic" ~ "Czech_Republic",
  TRUE ~ params$country
)

P <- P |> filter(year == 2026 & country == country_key)
```

# `r params$country` PopuList Country Report

::::: columns
::: {.column width="50%"}
## Party Overview
The column 'status' refers to whether the classification applies fully (●) or whether the party is a borderline case (◐).

```{r}
#| echo: FALSE
#| message: FALSE
#| warning: FALSE

library(purrr)
library(reactable)

populist_cleaned <- read_csv("/Users/lukefischer/Dropbox/The PopuList Repo/Data/processed_populist.csv")

populist_cleaned <- populist_cleaned |> mutate(Country = case_when(
  Country == "United Kingdom" ~ "United_Kingdom",
  Country == "Czech Republic" ~ "Czech_Republic",
  TRUE ~ Country
))

grouping_vars <- c("Populist", "Far-Right", "Far-Left", "Eurosceptic")

binded_result <- map_dfr(grouping_vars, function(var) {
  
  populist_cleaned |>
    filter(Country == country_key) |>
    select(`Party Name`, all_of(var), `In Parliament`) |>
    filter(.data[[var]] != "") |>
    rename("Status" = all_of(var), 
           "Party" = `Party Name`, 
            "Parliament" = `In Parliament`) |>
    mutate(Classification = var)  
})


reactable(
  binded_result,
  groupBy = "Classification", 
  columns = list(
    "Party" = 
      colDef(html = TRUE, width = 140, headerStyle = list(backgroundColor = "#f0f5f9")),
    "Status" = 
      colDef(html = TRUE, width = 140, headerStyle = list(backgroundColor = "#f0f5f9")),
    "Parliament" = 
      colDef(html = TRUE, width = 140, headerStyle = list(backgroundColor = "#f0f5f9")),
    "Classification" = 
      colDef(
        width = 140,
        headerStyle = list(backgroundColor = "#f0f5f9"),
        grouped = JS("function(cellInfo) {
        return cellInfo.value
      }")
      )),
  highlight = TRUE,
  sortable = TRUE,
  defaultExpanded = FALSE,
  defaultPageSize = 6,
  searchable = TRUE,
  theme = reactableTheme(
    borderColor = "#dfe2e5",
    stripedColor = "#f6f8fa",
    highlightColor = "#f0f5f9",
    cellPadding = "8px 12px",
    style = list(
      fontFamily = "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif"),
    searchInputStyle = list(width = "100%")
  )
)



```
:::

::: {.column width="50%" style="margin-bottom: -200px;"}
```{r}
#| echo: FALSE
#| message: FALSE
#| warning: FALSE

library(plotly)

plot_ly(
  type = "choropleth",
  locations = params$iso_code,          
  z = 1,          
  width = 465,  
  height = 465, 
  locationmode = "ISO-3",
  colorscale = list(c(0, 1), c("#FFB3F8", "#FFB3F8")),
  showscale = FALSE,
  marker = list(line = list(color = "#FFB3F8", width = 2))
) |> 
  layout(
    #margin = list(l=10, r=0, t=0, b=10),
    geo = list(
      projection = list(
        type = "orthographic",
        scale = 3
      ),
      center = list(
        lon = params$longitude,
        lat = params$latitude
      ),
      showland = TRUE,
      landcolor = "#e4e4e4",
      showcoastlines = TRUE,
      coastlinecolor = "#e4e4e4",
      showocean = TRUE,
      oceancolor = "#DFFFFE",
      bgcolor = "rgba(0,0,0,0)",
      framecolor = "rgba(0,0,0,0)"
    )
) |> 
  config(displayModeBar = FALSE)

```
:::
:::::

`r params$text`
